name: Make
on: [push]
jobs:
  makeIt:
    runs-on: ubuntu-latest
    steps:
      -
        name: Dependencies
        run: sudo apt install -y libgmp3-dev libmpc-dev libmpfr-dev
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Download binutils
        run: wget $(cat $GITHUB_WORKSPACE/binutils.txt)
      -
        name: Extract binutils
        run: tar xf binutils*.tar.xz
      -
        name: Compile binutils
        run: $GITHUB_WORKSPACE/cbinutils.sh
      -
        name: Download GCC
        run: wget $(cat $GITHUB_WORKSPACE/gcc.txt)
      -
        name: Extract GCC
        run: tar xf gcc*.tar.xz
      -
        name: Compile GCC
        run: $GITHUB_WORKSPACE/cgcc.sh
      -
        name: Compress binaries
        run: tar acf cross.tar cross/
      -
        name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cross.tar
